import React, { useState } from 'react';
import { Search, FlaskConical, AlertTriangle, CheckCircle2, ChevronRight, Activity } from 'lucide-react';

interface Ingredient {
  name: string;
  category: 'Exfoliant' | 'Retinoid' | 'Humectant' | 'Vitamin' | 'Protein' | 'Peptide';
  benefits: string[];
  risks: string[];
  compatibility: string;
  frequency: string;
  bestCombo: string;
  molecularWeight: string;
  clinicalSummary: string;
}

const INGREDIENTS_DATABASE: Ingredient[] = [
  {
    name: 'Retinol',
    category: 'Retinoid',
    benefits: ['Upregulates keratinocyte mitosis', 'Enhances collagen matrix density', 'Refines micro-wrinkles'],
    risks: ['Initial epidermal dryness/peeling', 'Elevated photosensitivity (UV susceptibility)', 'Contraindicated during pregnancy'],
    compatibility: 'Highly compatible with Hyaluronic Acid and Ceramides. Do not mix directly with Vitamin C or Salicylic Acid.',
    frequency: 'Nightly use (PM only), start with 2-3x per week.',
    bestCombo: 'Retinol + Ceramides (minimises skin barrier irritation)',
    molecularWeight: '286.45 g/mol',
    clinicalSummary: 'Vitamin A derivative that converts into retinoic acid inside skin cells. Upregulates deep cell division rates.'
  },
  {
    name: 'Niacinamide',
    category: 'Vitamin',
    benefits: ['Regulates sebaceous sebum output', 'Reduces post-inflammatory spots', 'Improves skin barrier lipids'],
    risks: ['Mild irritation in hyper-sensitive types if concentration exceeds 10%'],
    compatibility: 'Broadly compatible with all actives, including Retinol and Hyaluronic Acid.',
    frequency: 'Daily use (AM & PM).',
    bestCombo: 'Niacinamide + Salicylic Acid (regulates acne breakouts)',
    molecularWeight: '122.12 g/mol',
    clinicalSummary: 'Water-soluble Vitamin B3 compound. Inhibits transfer of pigment melanosomes to keratinocytes.'
  },
  {
    name: 'Hyaluronic Acid',
    category: 'Humectant',
    benefits: ['Attracts water up to 1000x its weight', 'Restores epidermal cell turgor', 'Smooths surface dehydration lines'],
    risks: ['Can pull moisture from deep dermis if applied in hyper-dry environments without sealant cream'],
    compatibility: '100% compatible across all ingredient categories.',
    frequency: 'Daily use (AM & PM).',
    bestCombo: 'Hyaluronic Acid + Vitamin C (boosts skin cell hydration glow)',
    molecularWeight: 'Multi-Weight (50k to 1.5M Da)',
    clinicalSummary: 'Glycosaminoglycan humectant. Rapidly pulls atmospheric and cellular moisture into the skin barrier.'
  },
  {
    name: 'Salicylic Acid',
    category: 'Exfoliant',
    benefits: ['Penetrates follicular lipid linings', 'Dissolves pore clogging debris', 'Reduces active acne redness'],
    risks: ['Mild stinging or temporary skin barrier drying if overused'],
    compatibility: 'Compatible with Niacinamide and Hyaluronic Acid. Avoid Retinol conflicts in the same application cycle.',
    frequency: '2-3x per week (PM preferred).',
    bestCombo: 'Salicylic Acid + Niacinamide (clears acne-prone follicles)',
    molecularWeight: '138.12 g/mol',
    clinicalSummary: 'Lipophilic beta-hydroxy acid (BHA). Unclogs follicular pathways by dissolving structural intercellular desmosomes.'
  },
  {
    name: 'Vitamin C (L-Ascorbic Acid)',
    category: 'Vitamin',
    benefits: ['Neutralizes daytime free radical ions', 'Inhibits melanogenesis (spots)', 'Boosts dermal collagen synthesis'],
    risks: ['Highly unstable; oxidises in UV light', 'Can cause mild tingling at low pH levels'],
    compatibility: 'Highly compatible with Vitamin E and Ferulic Acid. Do not mix directly with Retinol or Benzoyl Peroxide.',
    frequency: 'Daily use (AM preferred).',
    bestCombo: 'Vitamin C + Ferulic Acid (multiplies antioxidant power)',
    molecularWeight: '176.12 g/mol',
    clinicalSummary: 'Essential topical antioxidant. Scavenges free radical ions generated by daytime pollution and UV rays.'
  },
  {
    name: 'Biotin',
    category: 'Vitamin',
    benefits: ['Promotes keratin protein synthesis', 'Strengthens hair bulb shafts', 'Reduces nail plate peeling'],
    risks: ['No major topical risks', 'Ingested levels may affect thyroid blood assay readings'],
    compatibility: 'Compatible with rosemary oils, peptides, and caffeine complexes.',
    frequency: 'Daily use (AM or PM).',
    bestCombo: 'Biotin + Peptides (strengthens hair bulb roots)',
    molecularWeight: '244.31 g/mol',
    clinicalSummary: 'Water-soluble Vitamin B7 cofactor. Indispensable for cell growth and metabolism of keratin proteins.'
  },
  {
    name: 'Peptides (Copper Peptides)',
    category: 'Peptide',
    benefits: ['Upregulates skin cell tissue repair', 'Stimulates matrix collagen synthesis', 'Calms micro-vascular redness'],
    risks: ['Avoid mixing with direct acids (AHA/BHA) as low pH breaks down peptide bonds'],
    compatibility: 'Compatible with Niacinamide and Hyaluronic Acid.',
    frequency: 'Daily use (AM or PM).',
    bestCombo: 'Copper Peptides + Hyaluronic Acid (increases hydration recovery)',
    molecularWeight: '340.38 g/mol',
    clinicalSummary: 'Short-chain amino acid compounds that act as cellular messengers. Instruct cells to construct collagen.'
  }
];

export default function IngredientIntelligence() {
  const [query, setQuery] = useState('');
  const [selectedIngredient, setSelectedIngredient] = useState<Ingredient>(INGREDIENTS_DATABASE[0]);

  const filtered = INGREDIENTS_DATABASE.filter(item => 
    item.name.toLowerCase().includes(query.toLowerCase()) || 
    item.category.toLowerCase().includes(query.toLowerCase())
  );

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 animate-fadeIn text-aura-text">
      
      {/* Header */}
      <header className="mb-8">
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-purple-500/10 border border-purple-500/30 text-purple-400 mb-3">
          <FlaskConical size={12} /> Scientific Knowledge Base
        </span>
        <h1 className="text-3xl font-extrabold text-white font-display">Ingredient Intelligence Center</h1>
        <p className="text-sm text-aura-muted mt-1">Searchable clinical ingredient database detailing compound interactions, molecular weights, and compatibilities.</p>
      </header>

      {/* Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Search & List (5 Cols) */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          <div className="relative">
            <Search className="absolute left-3.5 top-3.5 text-aura-muted" size={16} />
            <input 
              type="text" 
              placeholder="Search Retinol, Niacinamide, Humectants..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-3 bg-black/45 border border-aura-border rounded-xl text-xs text-white focus:outline-none focus:border-purple-500/50 placeholder-aura-muted"
            />
          </div>

          <div className="flex flex-col gap-2 max-h-[480px] overflow-y-auto pr-1">
            {filtered.map(item => {
              const isActive = selectedIngredient.name === item.name;
              return (
                <button
                  key={item.name}
                  className={`p-4 rounded-xl border text-left transition-all flex justify-between items-center ${
                    isActive 
                      ? 'bg-purple-950/20 border-purple-500/50 shadow-glow-secondary' 
                      : 'bg-aura-panel border-aura-border hover:border-white/10'
                  }`}
                  onClick={() => setSelectedIngredient(item)}
                >
                  <div>
                    <h4 className="text-xs font-bold text-white mb-0.5">{item.name}</h4>
                    <span className="text-[10px] text-aura-muted font-mono">{item.category}</span>
                  </div>
                  <span className="text-[9px] text-purple-300 font-mono">{item.molecularWeight}</span>
                </button>
              );
            })}
            {filtered.length === 0 && (
              <div className="text-center py-8 text-xs text-aura-muted">No matching ingredients found.</div>
            )}
          </div>
        </div>

        {/* Right Column: Detail Profile Card (7 Cols) */}
        <div className="lg:col-span-7">
          <div className="p-6 rounded-2xl bg-aura-panel border border-aura-border glass-gradient">
            
            <div className="flex justify-between items-start border-b border-aura-border pb-4 mb-6">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-purple-400 font-mono">Molecular profiling</span>
                <h3 className="text-xl font-bold text-white mt-0.5">{selectedIngredient.name}</h3>
                <p className="text-[11px] text-aura-muted mt-1 leading-relaxed">{selectedIngredient.clinicalSummary}</p>
              </div>
              <span className="text-[10px] font-bold px-2.5 py-1 border border-purple-500/20 bg-purple-500/5 rounded-full text-purple-400">
                {selectedIngredient.category}
              </span>
            </div>

            {/* Profile Info Cards */}
            <div className="flex flex-col gap-4">
              
              {/* Benefits */}
              <div>
                <h4 className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <CheckCircle2 size={12} /> Clinical Benefits
                </h4>
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {selectedIngredient.benefits.map((b, idx) => (
                    <li key={idx} className="text-[10px] text-white/90 bg-emerald-500/5 border border-emerald-500/10 p-2 rounded-lg">
                      ✓ {b}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Risks */}
              <div>
                <h4 className="text-[10px] font-bold text-rose-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <AlertTriangle size={12} /> Potential Side Effects / Risks
                </h4>
                <ul className="flex flex-col gap-1.5">
                  {selectedIngredient.risks.map((r, idx) => (
                    <li key={idx} className="text-[10px] text-white/80 bg-rose-500/5 border border-rose-500/10 p-2 rounded-lg">
                      ⚠️ {r}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Stats */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-aura-border">
                <div>
                  <h5 className="text-[10px] font-bold text-aura-muted uppercase mb-1">Compatibility Profile</h5>
                  <p className="text-[10px] text-white leading-relaxed">{selectedIngredient.compatibility}</p>
                </div>
                <div>
                  <h5 className="text-[10px] font-bold text-aura-muted uppercase mb-1">Recommended Usage Frequency</h5>
                  <p className="text-[10px] text-white leading-relaxed">{selectedIngredient.frequency}</p>
                </div>
              </div>

              {/* Combo */}
              <div className="p-3.5 rounded-xl bg-purple-950/10 border border-purple-500/10 text-[10px] text-white/95 mt-2">
                <span className="font-bold text-purple-300">Optimal Synergy Combo:</span> {selectedIngredient.bestCombo}
              </div>

            </div>

          </div>
        </div>

      </div>

    </div>
  );
}
